name: 'Infrastructure Setup'

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
        
    # Setup Terraform
    - name: Save PrivateKey
      run: |
        ls -ltra
        echo ${{ secrets.VM_PUBLIC_KEY }} > terraform/id_rsa.pub
    
    # Determine Environment
    - name: Determine Environment
      id: env
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "env=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
        else
          echo "env=dev" >> $GITHUB_OUTPUT
        fi  
    
    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init -backend-config="key=terraform-${{ steps.env.outputs.env }}.tfstate"
      working-directory: terraform

    # Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

    # Format Terraform files
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    # Plan Terraform deployment
    - name: Terraform Plan
      run: terraform plan --var-file="terraform-${{ steps.env.outputs.env }}.tfvars" -out=tfplan
      working-directory: terraform

    # Apply Terraform configuration (only on push to main)
    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve tfplan
     

